CREATE TABLE IF NOT EXISTS "squishes-checkers_allowed_email_new" (
\t"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "squishes-checkers_allowed_email_new_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
\t"email" varchar(255) NOT NULL,
\t"isAdmin" boolean DEFAULT false NOT NULL,
\t"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
\tCONSTRAINT "squishes-checkers_allowed_email_new_email_unique" UNIQUE("email")
);
--> statement-breakpoint

INSERT INTO "squishes-checkers_allowed_email_new" ("id", "email", "isAdmin", "createdAt")
SELECT "id", "email", false, "createdAt" FROM "squishes-checkers_allowed_email";
--> statement-breakpoint

DROP TABLE "squishes-checkers_allowed_email";
--> statement-breakpoint

ALTER TABLE "squishes-checkers_allowed_email_new" RENAME TO "squishes-checkers_allowed_email";
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "email_idx" ON "squishes-checkers_allowed_email" USING btree ("email");